-- Migration 0001: Create diagrams table
-- PostgreSQL 16 schema per design.md "Persistence Schema"

CREATE TABLE IF NOT EXISTS diagrams (
  id         uuid PRIMARY KEY,            -- uuidv7, generated by the API
  name       text NOT NULL,               -- listing label
  doc        jsonb NOT NULL,              -- readable projection of the IR
  yjs_state  bytea NOT NULL,              -- binary Yjs update blob (authoritative)
  version    integer NOT NULL DEFAULT 1,  -- optimistic concurrency counter
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_diagrams_updated ON diagrams (updated_at DESC);

-- Migration tracking table
CREATE TABLE IF NOT EXISTS _migrations (
  id         integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  filename   text NOT NULL UNIQUE,
  applied_at timestamptz NOT NULL DEFAULT now()
);